// Mocks generated by Mockito 5.4.4 from annotations
// in flutter_manga_sync/test/features/manga/data/datasources/manga_local_datasource_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes

import 'dart:async' as _i3;

import 'package:flutter_manga_sync/features/manga/data/datasources/manga_local_datasource.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [MangaLocalDataSource].
///
/// See the documentation for Mockito's code generation for more information.
class MockMangaLocalDataSource extends _i1.Mock
    implements _i2.MangaLocalDataSource {
  MockMangaLocalDataSource() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<void> cacheMangas(List<dynamic>? mangasJson) =>
      (super.noSuchMethod(
        Invocation.method(
          #cacheMangas,
          [mangasJson],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  List<dynamic> getCachedMangas() => (super.noSuchMethod(
        Invocation.method(
          #getCachedMangas,
          [],
        ),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  List<dynamic> getFavorites() => (super.noSuchMethod(
        Invocation.method(
          #getFavorites,
          [],
        ),
        returnValue: <dynamic>[],
      ) as List<dynamic>);

  @override
  bool isFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #isFavorite,
          [id],
        ),
        returnValue: false,
      ) as bool);

  @override
  _i3.Future<void> saveFavorite(Map<String, dynamic>? mangaMap) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveFavorite,
          [mangaMap],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);

  @override
  _i3.Future<void> removeFavorite(String? id) => (super.noSuchMethod(
        Invocation.method(
          #removeFavorite,
          [id],
        ),
        returnValue: _i3.Future<void>.value(),
        returnValueForMissingStub: _i3.Future<void>.value(),
      ) as _i3.Future<void>);
}
